###############################################################################
# GNUmakefile :: This Makefile works as a front-end to other Make Utilities.  #
###############################################################################

#
# Include the forwarder.
#
include		../../INCLUDE/MAKEFRWD.MIF
