
#define TXT_QUERY_TimeLimit_None          860
#define TXT_QUERY_TimeLimit_Show          861
#define TXT_QUERY_Mode_Extended           863
#define TXT_QUERY_Mode_Normal             864
#define TXT_SYNTAX_Show                   867
#define TXT_ERROR_DuringAccessHDD         868
#define TXT_ERROR_NoValueFor              870
#define TXT_ERROR_NeedsValueFor           871
#define TXT_ERROR_BadParameter            872
#define TXT_ERROR_BadValueFor             873
#define TXT_ERROR_NoBootManager           874
