###############################################################################
# GNUmakefile :: Master Entrypoint for the 'GNU Make' build utility           #
# --------------------------------------------------------------------------- #
# GNU Make always first looks for a file called 'GNUmakefile' before looking  #
# for the usual 'Makefile' or 'makefile' names. To enable a flexible build    #
# environment, this 'GNUmakefile' redirects 'make' to the actual commands to  #
# do the building. Such a redirection can be as simple as just including the  #
# real GNU Makefile to invoking other (foreign) build tools.                  #
###############################################################################

# Simply include the real GNU Makefile
include airboot-manual.gmk
