/* REXX */

date_file = 'BLDDATE.ASM';

/* 
Supported languages are: EN,DE,FR,SW,IT,NL,RU.
Change lang to 'ALL' to build all language versions. 
*/
lang = 'EN';

/* Generate BUILD_DATE.ASM  */
"@echo: BUILD_DATE: db 'Build Date: "||Date()||" at "||Time()||"',0    ; Generated by _build.cmd > "||date_file;
'@CALL MAKEALL.BAT '||lang;
Say '';
Say '';
Say '';
Say '#';
Say '# Language versions are in: RELEASE\BOOTCODE';
Say '# If ALL languages are built the English version is copied to RELEASE\<PLATFORM> as AIRBOOT.BIN';
Say '# If ONE language  is built this Language version is copied to RELEASE\<PLATFORM> as AIRBOOT.BIN';
Say '#';
Say '';
'rem @pause';
